# Generated by Django 5.2.17 on 2026-09-17 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(help_text='Unique numeric identifier for the student', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full Name of the student', max_length=100)),
                ('email', models.EmailField(help_text='Unique email address', max_length=254, unique=True)),
                ('department', models.CharField(choices=[('AI & Data Science', 'AI & Data Science'), ('Computer Science Engineering', 'Computer Science Engineering'), ('Information Technology', 'Information Technology'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering')], help_text='Academic department', max_length=100)),
                ('year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], help_text='Academic year (1, 2, 3, or 4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number (7 to 15 digits).', regex='^\\+?[0-9\\s\\-()]{7,15}$')])),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
    ]
